name: GitHub Practise
on: workflow_dispatch
jobs:
  Dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create a folder
        run: mkdir Harishfile
      - name: Print My Name
        run: echo "Hello Harish">>hello.txt
